AllCops:
  NewCops: disable

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  CountComments: false
  Max: 25
  Exclude:
    - config/environments/*
    - config/initializers/simple_form_bootstrap.rb
